Arch4edu mirrorlist as a package
arch4edu/arch4edu pull request #125
Opened 2021-05-20 03:43 UTC by heavysink

Hi,

I think we can package our mirrorlist in this repository. It will follow the updates from arch4edu/mirrorlist. If possible, we may edit the wiki of how to add arch4edu to Archlinux about it.

2021-05-20 06:14 UTC, petronny requested changes

2021-05-20 06:15 UTC, petronny commented
> If possible, we may edit the wiki of how to add arch4edu to Archlinux about it.

先有鸡还是先有蛋的问题。添加一个源的时候还是得手动查的。
不过这个包可以用给 docker image

2021-07-04 14:16 UTC, SamLukeYes commented
> 先有鸡还是先有蛋的问题。添加一个源的时候还是得手动查的。
可以参考 [chaotic-aur](https://aur.chaotic.cx/) 的做法，让用户通过直链下载安装 keyring 和 mirrorlist 就有蛋了

2021-12-30 02:25 UTC, heavysink commented on arch4edu-mirrorlist-git/PKGBUILD
> +  cp "mirrorlist.arch4edu" "$pkgdir/etc/pacman.d/$_mirrorlist_name"
改好了，见新commit

2021-12-30 02:25 UTC, heavysink commented on arch4edu-mirrorlist-git/PKGBUILD
> +pkgname=$_mirrorlist_name-git
改好了，见新commit

2021-12-30 02:26 UTC, heavysink commented
我全部改好了，你可以看看 @petronny

2021-12-30 02:31 UTC, heavysink commented on arch4edu-mirrorlist-git/lilac.py
> +  run_cmd(["rm", "-rf", "mirrorlist"])
改好了

2022-06-11 14:13 UTC, closed without merging

2022-06-13 12:55 UTC, petronny commented
调试cactus时，不小心把 git 记录给清了。。。你能再发一下这个么？