Add mms-git
arch4edu/arch4edu pull request #243
Opened 2023-10-10 19:03 UTC by KenwoodFox

From: https://aur.archlinux.org/packages/mms-git

Me and my robotics team are hoping we can get this added as a pebuild package!

2023-10-11 05:42 UTC, petronny requested changes

2023-10-11 05:42 UTC, petronny commented on any/mms-git/cactus.yaml
> +    aur:
Please also add a `github` source for a git package.

```yaml
  - source: github
    github: mackorone/mms
```

2023-10-11 05:49 UTC, petronny commented
Hi, this package doesn't seem to be an `any` package. Please confirm and if it isn't an `any` package:

1. Move `any/mms-git/cactus.yaml` to `x86_64/mms-git/cactus.yaml`
2. Please contact the maintainer on AUR to set `arch=('x86_64')` in PKGBUILD.
3. If the maintainer doesn't respond, update the `pre_build` in `cactus.yaml` to set `arch=('x86_64')`:
```yaml
pre_build: |
  aur-pre-build
  echo "arch=('x86_64')" >> PKGBUILD
```

2023-10-11 23:21 UTC, KenwoodFox commented
> Hi, this package doesn't seem to be an `any` package. Please confirm and if it isn't an `any` package:
> 
>     1. Move `any/mms-git/cactus.yaml` to `x86_64/mms-git/cactus.yaml`
> 
>     2. Please contact the maintainer on AUR to set `arch=('x86_64')` in PKGBUILD.
> 
>     3. If the maintainer doesn't respond, update the `pre_build` in `cactus.yaml` to set `arch=('x86_64')`:
> 
> 
> ```yaml
> pre_build: |
>   aur-pre-build
>   echo "arch=('x86_64')" >> PKGBUILD
> ```

Hey! Thanks for responding, i checked around and i don't *think* there's any reason this couldn't be compiled for other arches? I checked on the aur and the github and everything *seems* to be architecture agnostic, not sure about upstream libs of course.

Regardless, I dont anticipate anybody will complain if this package is x86_64 only so, I'll implement the suggested patch, and thank you!

2023-10-12 06:03 UTC, petronny commented
> Hey! Thanks for responding, i checked around and i don't think there's any reason this couldn't be compiled for other arches? I checked on the aur and the github and everything seems to be architecture agnostic, not sure about upstream libs of course.

Hi, to be an `any` package means that its final compiled binary is cross-platform, like the binary built on an x86_64 machine also runs on an ARM board.

If the code is cross-platform but the binary isn't, we should set `arch` to all supported platform like:
```
arch=('x86_64' 'i686' 'aarch64' 'armv6h' 'armv7h')
```

2023-10-12 06:20 UTC, KenwoodFox commented
> > Hey! Thanks for responding, i checked around and i don't think there's any reason this couldn't be compiled for other arches? I checked on the aur and the github and everything seems to be architecture agnostic, not sure about upstream libs of course.
> 
> Hi, to be an `any` package means that its final compiled binary is cross-platform, like the binary built on an x86_64 machine also runs on an ARM board.
> 
> If the code is cross-platform but the binary isn't, we should set `arch` to all supported platforms like:
> 
> ```
> arch=('x86_64' 'i686' 'aarch64' 'armv6h' 'armv7h')
> ```

Ah I understand now, i thought any would essentially do that, just make a bin for each major arch. Since I'm unsure about the availability of the upstream qt libs, lets just see if this compiles for arch4edu now? i can implement that suggested change rn if you would like

2023-10-12 07:23 UTC, petronny commented on any/mms-git/cactus.yaml
> +    aur:
Hi, please also add the `aur` upstream.

2023-10-13 05:35 UTC, KenwoodFox commented
Does this build? I dont see its status in the build pages

2023-10-13 06:12 UTC, petronny requested changes

2023-10-13 06:12 UTC, petronny commented on x86_64/mms-git/cactus.yaml
> +    github: mackorone/mms
Hi, please also add the `aur` upstream.
```yaml
nvchecker:
  - source: aur
    aur:
  - source: github
    github: mackorone/mms
```

2023-10-15 00:59 UTC, KenwoodFox commented on x86_64/mms-git/cactus.yaml
> +    github: mackorone/mms
Ok! Added in 4624f3e1

2023-10-15 05:30 UTC, petronny approved these changes

2023-10-15 05:30 UTC, merged

2023-10-15 12:52 UTC, petronny commented
https://github.com/arch4edu/cactus/actions/runs/6524159790/job/17715533270

2023-10-15 12:55 UTC, KenwoodFox commented
Wooo yeah!